# Base configs
baseurl: ""
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Ian Lowe     All Images © Ian Lowe 2026"
subtitle: "See the world through my eyes!"
author: "Ian Lowe"
header:
 title: "Photography"
 subtitle: "by Ian Lowe"
footer:
 name: "Hey there, my name is Ian"
 bio: 'My fascination with photography began in the darkroom at Sunderland art college.  Recalling the "alchemy" of seeing a B&W landscape of Southwold materialise in the developing tray; is what first drew me to photography. While my career took me into the worlds of technical illustration and Formula One, that fundamental curiosity never left me. I am particularly interested in the "grittiness" of early 20th-century photography, from the very start with the work of Fox Talbot to the graphic power of First World War imagery. I want to research how these early types of photography compare to modern technology, perhaps by shooting the same subject on everything from salt paper prints to an iPhone to see how the process alters the message.'

social_urls:
  linkedin: "https://in.linkedin.com/in/ianlowe3mil"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
