# Base configs
baseurl: "sootyian.github.io"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Ian Lowe"
subtitle: "See the world through my eyes!"
author: "Ian Lowe"
header:
 title: "Photography"
 subtitle: "by Ian Lowe"
footer:
 name: "Hey there, my name is Ian"
 bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet elit sed magna placerat accumsan vulputate vitae tortor. Curabitur sodales pulvinar sollicitudin. Duis vitae maximus enim, et blandit nulla. Integer id ligula ut orci ultrices varius. Vestibulum vehicula vehicula turpis et aliquam. Vivamus accumsan egestas dui, a efficitur ex placerat non. Mauris sed ornare arcu, sit amet fringilla libero."

social_urls:
  linkedin: "https://in.linkedin.com/in/ianlowe3mil"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
